### ISSUE TITLE
[Suggestion]Adds Mod Support for Simply Skills

### ISSUE THREAD

**Issue by MoneySoup008** [Reniel80/Legendary-Origins#1]
This is an suggestion request:
It would be great to add support for simply skills because legendary origins rpg style suits to "simply skills", and their skill trees are just perfect for combination. I think it would be great that you consider for your next update.

**Comment by Reniel80** [comment]
A skill tree for Legendary Origins classes is scheduled for next development stage `Spoiler 🤫` and you are right about it, the compatibility between both is very interesting. Although "Simply Skills" is still in its beta phase it looks promising.
