### ISSUE TITLE
All the origins are gone!

### ISSUE THREAD

**Issue by Meeklly** [Reniel80/Legendary-Origins#3]
I downloaded Legendary Origins for a mopack and when I open a new world only dwarf is shown.
![image_2023-12-01_235508678](https://github.com/Reniel80/Legendary-Origins/assets/152681290/f602b372-d40e-4f5d-a09f-532855729c73)

**Comment by Reniel80** [comment]
Are you using any other mod that modify origins default settings?

• Please, verify if you are using the correct origins dependency version and no other origins addon.
• Legendary Origins is designed to manage only its own Races, Classes and Professions.
• This will provide a fair balance for players who wish to live immersive experiences in a RPG-PVP world using only this thematic.

**Comment by Reniel80** [comment]
Are you using any other mod that modify origins default settings?

• Please, verify if you are using the correct origins dependency version and you are not using any other origins addon.
• Legendary Origins is designed to manage only its own Races, Classes and Professions.
• This will provide a fair balance for players who wish to live immersive experiences in a RPG-PVP world using only this thematic.

**Comment by Reniel80** [comment]
Are you using any other mod that modify origins default settings?

• Please, verify if you are using the correct and recent origins dependency version and you are not using any other origins addon.
• Legendary Origins is designed to manage only its own Races, Classes and Professions.
• This will provide a fair balance for players who wish to live immersive experiences in a RPG-PVP world using only this thematic.

**Comment by Reniel80** [comment]
Are you using any other mod that modify origins default settings?

• Please, verify if you are using the correct and recent origins dependency version and you are not using any other origins addon.
• Legendary Origins is designed to manage only its own Races, Classes and Professions. Default Origins are not included.
• This will provide a fair balance for players who wish to live immersive experiences in a RPG-PVP world using only this thematic.

**Comment by Reniel80** [comment]
Are you using any other mod that modify origins default settings?

• Please, verify if you are using the proper and recent origins dependency version and you are not using any other origins addon.
• Legendary Origins is designed to manage only its own Races, Classes and Professions. Default Origins are not included.
• This will provide a fair balance for players who wish to live immersive experiences in a RPG-PVP world using only this thematic.

**Comment by Meeklly** [comment]
no this happens regardless if  I have other origins or not and it happens with all origins just obviously with different ones

**Comment by Reniel80** [comment]
Minecraft version?
Loader version?
Legendary Origins version?
Any other mods that interact with origins?

**Comment by Reniel80** [comment]
Your Minecraft version?
Your Loader version?
Your Legendary Origins version?
Any other mods that interact with origins?

I would like to reproduce this problem... can you write me the list of your mods to detect what is the cause?

PD. Legendary Origins is designed to show only its content. It is not compatible with other Origins addons, even if it uses Origins libraries as a dependency.

**Comment by Reniel80** [comment]
Your Minecraft version?
Your Loader version?
Your Legendary Origins version?
Any other mods that interact with origins?

I would like to reproduce this issue... can you write me the list of your mods to detect what is the cause?

PD. Legendary Origins is designed to show only its content. It is not compatible with other Origins addons, even if it uses Origins libraries as a dependency.

**Comment by Reniel80** [comment]
Your Minecraft version?
Your Loader version?
Your Legendary Origins version?
Any other mods that interact with origins?

I would like to reproduce this issue... can you write me the list of the mods you are using to detect what is the cause?

PD. Legendary Origins is designed to show only its content. It is not compatible with other Origins addons, even if it uses Origins libraries as a dependency.

**Comment by Reniel80** [comment]
Your Loader version?
Your Legendary Origins version?
Any other mods that interact with origins?

I would like to reproduce this issue... please, if it's possible, can you send here the modpack to detect what is the cause?

PD. Legendary Origins is designed to show only its content. It is not compatible with other Origins addons, even if it uses Origins libraries as a dependency.

**Comment by Reniel80** [comment]
Your Loader version?
Your Legendary Origins version?
Any other mods that interact with origins?

I would like to reproduce this issue... please, if it's possible, can you send here the modpack or the list of used mods to detect what is the cause?

PD. Legendary Origins is designed to show only its content. It is not compatible with other Origins addons, even if it uses Origins libraries as a dependency.

**Comment by Reniel80** [comment]
Your MInecraft version?
Your Loader version?
Your Legendary Origins version?
Any other mods that interact with origins?

I would like to reproduce this issue... please, if it's possible, can you send here the modpack or the list of used mods to detect what is the cause?

PD. Legendary Origins is designed to show only its content. It is not compatible with other Origins addons, even if it uses Origins libraries as a dependency.

**Comment by Reniel80** [comment]
You are using a Fabric API version superior to 0.90.7
Fabric API  0.90.7 is the latest supported version for Origins 1.11.3

**Comment by Reniel80** [comment]
You are using a Fabric API version superior to 0.90.7
Fabric API 0.90.7 is the latest compatible version for Legendary Origins 2.0.1 and previous versions.
